### ISSUE TITLE
Initial prototype

### ISSUE THREAD

**Issue by hannahaker** [SDSMT-CSC464-F15/crowdscience#6]
For our initial prototype, we need to configure the Apache server for hosting our project with a different domain, pointing to a different directory. After we do this, we need to create a rudimentary index page and java script page and access the Mongo database. We need to consider creating a new Mongo database for use with our project, but creating the new database can be pushed back a sprint. We also need to consider using github on the server, but before we do, we need to know how to have git only sync our source code, not all the documentation with the server.

**Comment by hannahaker** [comment]
A good resource for Java Script: http://www.w3schools.com/js/default.asp

**Comment by jiasongyan** [comment]
There is a git on the server, and I cloned my test repository on Documents folder by running it and simply type HTTPs clone URL, but that is the whole thing instead of the code only.

**Comment by jiasongyan** [comment]
As for the first step, I scan some examples on website and try to configure Apache server by modifying httpd.conf in Apache2.2/conf and httpd-vhosts.conf in Apache2.2/conf/extra. But I failed with 404 or 403 error after I restart Apache. Now I just restore those 2 files.

**Comment by hannahaker** [comment]
I'll look at this tomorrow after classes, and see what I can figure out. If I don't find anything, we can put our heads together on Thursday. In the meantime, we can be working on the list of requirements.

**Comment by jiasongyan** [comment]
I guess I figure out the virtual host for Apache. And u can check that on the website http://54.244.242.86/. Here shows a branch for our webpage. The domain name like www.crowdsciencemap.com is not available since it requires registration and might not be free.

**Comment by hannahaker** [comment]
Looks awesome like that, it works. We should start putting source files into the Source folder (even if they consist of "This is a Header")

**Comment by jiasongyan** [comment]
I will try to work on some features on that webpage tonight as u mentioned on step 2, but leave Mongo database alone since I totally have no idea about that at the moment. We can have a discuss with document part like sprint report tomorrow after class on lab room.

**Comment by hannahaker** [comment]
https://mongodb.github.io/node-mongodb-native/api-articles/nodekoarticle1.html looks like a good starting point for Mongo DB. I'll look at that some tonight. Then, yes, let's meet after class tomorrow, the sprint report shouldn't be too hard.
